title: RecylRoute
description: Webroutenberechung für Recyclingsammlungen
navigation: main
remote_theme: pages-themes/minimal
source: docs
logo: Bilder/RecyclRoute_Logo.png
baseurl: "/RecyclRoute"
url: "https://recyclroute.github.io"
markdown: kramdown
kramdown:
  input: GFM

