<<<<<<< Updated upstream
title: FootballMap
description: Interaktive Fussball-Karte
navigation: main
theme: jekyll-theme-minimal
=======
theme: jekyll-theme-minimal
title: RecyclRoute
description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!
>>>>>>> Stashed changes
